### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gumernus** [VojtaG/BinaryToDecimal-ConsoleApp#1]
**Systém Windows nemá přístup k určenému zařízení, cestě nebo souboru. K přístupu k položce pravděpodobné nemáte patřičná oprávnění.**

Idk tohle se mi stalo pokaždé co jsem chtěl spustit nějakej .exe konzolovej program. nevíš co s tím?

**Comment by vojtechgistr** [comment]
No.. tohle je dost náročný problém, který může být způsoben dokonce i špatnou verzí windowsu. 
Doporučuji pročíst tohle fórum, máš tam minimálné 3 řešení:

https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/cant-open-exe-files-windows-10/fbb1fde7-aafa-4dc8-9ecb-873dbeb4518e?page=2

**Comment by gumernus** [comment]
nevím jak to myslíš ale nejdou my otevřít jen dev community programy. Třeba jako ten tvůj atd od jiných rádoby devs. Ostatní programy jdou v pohodě otevřít jeeen tyhle ne no

**Comment by vojtechgistr** [comment]
No tak to vůbec netuším.. Buď to blbě otevíráš, nebo nevím

**Comment by gumernus** [comment]
Ono idk nooo Lolt (kamarád) mi taky poslal jeho autoclicker a nešlo to ale t tam byl zase jinej problém hmmmmmm

**Comment by Dargrik** [comment]
Zkus si prostě nastavit ve windows na uživatele administrátora

**Comment by gumernus** [comment]
to je tru aaale jak xdd?

**Comment by gumernus** [comment]
je pravda že některý commandy mi jdou jen přes PowerShell
